### ISSUE TITLE
http_host_aliases not working

### ISSUE THREAD

**Issue by eladnova** [Mark-H/ContextRouter#10]
Hi Mark
Should this work with 2.2.16?

I have a 5 Context site and one of the Contexts needs to be accessed from 2 different domains.

On that particular domain, I have added a Context setting called **http_host_aliases** and specified 
domain.com, domain2.org
in the value field.

After flushing the cache several times, domain2.org still insists on loading Context01 instead of Context05

Wondering if this was a known bug?

**Comment by Mark-H** [comment]
Yeah I'd expect it to work. What's in your contextrouter cache file? Should be under core/cache/default/ I think, or core/cache/system_settings/

**Comment by eladnova** [comment]
Mark - thanks for pointing me in that direction.
There were no spaces in my value field but the cached file showed spaces from an earlier attempt.
All sorted and working now.

**Comment by Mark-H** [comment]
Great!
