### ISSUE TITLE
general problem

### ISSUE THREAD

**Issue by pawelmil** [Mark-H/ContextRouter#8]
I used context router with 2 domains configuration. It doesn't work now and I can' find reason: it redirects both domains to one site . 
During cache refrest I have log: [ContextRouter] You may have conflicting http_host definitions. Overwriting context web with domain2 for host www.domain2.com
How can I find where the problem is?
modx 2.3.2 contextrouter 1.1.0-pl2

**Comment by Mark-H** [comment]
Sorry for not responding sooner, didn't see the notification. You can review the cache file to see how it interpreted your settings and how it will route them. IIRC that should be under core/cache/default/contextrouter.cache.php

**Comment by depositado** [comment]
I have the same issue Mark, the contextrouter.cache.php gives me the following:
```
<?php  return array (
  'default' => 'env2',
  'www.dev.domain.com' => 'web',
  'dev.domain.com' => 'web',
  'www.domain.com' => 'env2',
  'domain.com' => 'env2',
);
```

When I empty the cache, contextrouter.class.php (line 72) logs this error:

[ContextRouter] You may have conflicting http_host definitions. Overwriting context web with env2 for host www.domain.com

It's not clear what exactly is considered 'conflicting'. I assume there is something wrong with the following line:
```
if (isset($this->routes['www.' . $host]) && ($this->routes['www.' . $host] != $ctx)) {
```

**Comment by depositado** [comment]
Hey Mark, these are my context settings:

context "web":
http_host 	dev.teqoia.com
http_host_aliases  (EMPTY)

context "env2":
http_host 	teqoia.com
http_host_aliases 	www.teqoia.com

the http_host_aliases for context 'env2' shouldn't be necessary because system setting "contextrouter.includeWww" is set to true.
