### ISSUE TITLE
Issue with ContextRouter and using Forced SSL Rewrite Rules

### ISSUE THREAD

**Issue by supasmo** [Mark-H/ContextRouter#9]
ContextRouter was working great. I added a web rule to force rewrite for SSL. After that the subdomains no longer routed to the correct location. **Has there been any known issues with adding a SSL rewrite rule and ConextRouter no longer working properly?** I'm using modxcloud and the nginx web rules. Attached here is the rewrite that interferes with context router.

`add_header Strict-Transport-Security "max-age=31536000; includeSubdomains"; 
if ($scheme != "https") {
    rewrite ^ https://$host$uri permanent;
}
if ($host != "www.onesourcevirtual.com") {
    rewrite ^ https://www.onesourcevirtual.com$uri permanent;
}`

**Comment by Mark-H** [comment]
No, I'm not aware of any known issues with SSL rewrites. The only thing I can come up with is that the hosts might come through to MODX with `:443` but I'm pretty sure I've used ContextRouter on HTTPS sites before without issue..
